version: "3"

services:
  mysql-database:
    image: mysql
    ports:
      - ${DATABASE_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASS}
      - MYSQL_DATABASE=${DATABASE_NAME}
    volumes:
      - ./.db_data:/var/lib/mysql

  test-mysql-database:
    image: mysql
    ports:
      - ${TEST_DATABASE_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${TEST_DATABASE_PASS}
      - MYSQL_DATABASE=${TEST_DATABASE_NAME}
